[package]
name = "crt_eg"
version = "0.1.0"
authors = ["Alex Myers", "Kristofer Rye <kristofer.rye@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "*"
